---

apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: chaos-demo
spec:
  containers:
    - name: nginx
      image: 049780446181.dkr.ecr.ap-south-1.amazonaws.com/spark:nginx-test
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 10
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 20Mi